In [37]:
import pandas 
import numpy as np
df = pandas.read_csv('Xak.csv')
df

Time  Mood  Reason  Category  Subcategory  Result(%)  User ID
0      187     1       2         5            2         88        1
1       99     1      23         6            1         92        1
2      269     1       7         4            3         71        1
3      158     1      15         5            4         81        1
4      236     1       3         3            2         76        1
...    ...   ...     ...       ...          ...        ...      ...
2995   283     3       8         2            2         10        3
2996   124     3       6         1            2          2        3
2997   158     3      13         3            1         21        3
2998   292     3       2         5            2         25        3
2999   286     3      12         1            1         19        3

[3000 rows x 7 columns]

In [38]:
df = df.drop('User ID', axis = 1)
df

Time  Mood  Reason  Category  Subcategory  Result(%)
0      187     1       2         5            2         88
1       99     1      23         6            1         92
2      269     1       7         4            3         71
3      158     1      15         5            4         81
4      236     1       3         3            2         76
...    ...   ...     ...       ...          ...        ...
2995   283     3       8         2            2         10
2996   124     3       6         1            2          2
2997   158     3      13         3            1         21
2998   292     3       2         5            2         25
2999   286     3      12         1            1         19

[3000 rows x 6 columns]

In [39]:
df =df[~df.isin([np.nan, np.inf, -np.inf]).any(1)]
df

Time  Mood  Reason  Category  Subcategory  Result(%)
0      187     1       2         5            2         88
1       99     1      23         6            1         92
2      269     1       7         4            3         71
3      158     1      15         5            4         81
4      236     1       3         3            2         76
...    ...   ...     ...       ...          ...        ...
2995   283     3       8         2            2         10
2996   124     3       6         1            2          2
2997   158     3      13         3            1         21
2998   292     3       2         5            2         25
2999   286     3      12         1            1         19

[3000 rows x 6 columns]

In [40]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)
from sklearn.model_selection import train_test_split

In [41]:
y= df['Subcategory']
y

0       2
1       1
2       3
3       4
4       2
       ..
2995    2
2996    2
2997    1
2998    2
2999    1
Name: Subcategory, Length: 3000, dtype: int64

In [42]:
X = df.drop('Subcategory', axis =1)
X

Time  Mood  Reason  Category  Result(%)
0      187     1       2         5         88
1       99     1      23         6         92
2      269     1       7         4         71
3      158     1      15         5         81
4      236     1       3         3         76
...    ...   ...     ...       ...        ...
2995   283     3       8         2         10
2996   124     3       6         1          2
2997   158     3      13         3         21
2998   292     3       2         5         25
2999   286     3      12         1         19

[3000 rows x 5 columns]

In [43]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.20, random_state=42)

In [44]:
y_test

1801    2
1190    3
1817    2
251     3
2505    3
       ..
104     1
2087    1
599     3
1756    4
1323    3
Name: Subcategory, Length: 600, dtype: int64

In [45]:
X_train

Time  Mood  Reason  Category  Result(%)
642    177     1      16         4         76
700    271     1       2         4         93
226    223     1      14         2         88
1697   277     2       4         6         44
1010   231     1      17         2         47
...    ...   ...     ...       ...        ...
1638   204     2      15         1         58
1095   289     1       9         5         53
1130   187     2      10         1         65
1294    80     2       5         5         65
860    142     1      14         2         71

[2400 rows x 5 columns]

In [46]:
y_train

642     1
700     3
226     2
1697    4
1010    3
       ..
1638    3
1095    3
1130    2
1294    3
860     3
Name: Subcategory, Length: 2400, dtype: int64

In [47]:
neigh.fit(X,y)


KNeighborsClassifier()

In [48]:
neigh.score(X_train, y_train)

0.525

Берем первую строку

In [49]:
for_test = df.iloc[[1]] 
for_test = for_test.drop('Subcategory', axis =1)
for_test

Time  Mood  Reason  Category  Result(%)
1    99     1      23         6         92

Ниже предскзание категории для этой модели

In [50]:
neigh.predict(for_test)

array([4])

Экпортируем модель в файл

In [51]:
import pickle

In [52]:
filename = 'finalized_model.sav'
pickle.dump(neigh, open(filename, 'wb'))

Чтение модели из файла

In [53]:
loaded_model = pickle.load(open(filename, 'rb'))


Проверяем 

In [54]:
for_test = df.iloc[[111]] 
for_test = for_test.drop('Subcategory', axis =1)
for_test

Time  Mood  Reason  Category  Result(%)
111   274     1       6         4         80

In [55]:
loaded_model.predict(for_test)

array([4])

Так как обычно весь обмен с беком от приложения происходит через json то надо понять его структуру

In [56]:
result = for_test.to_json(orient="records")

In [57]:
result

'[{"Time":274,"Mood":1,"Reason":6,"Category":4,"Result(%)":80}]'

Создадим json с новыми данными

In [58]:
test2 = '[{"Time":888,"Mood":2,"Reason":1,"Category":2,"Result(%)":20}]'

In [59]:
df_test = pandas.read_json(test2)
df_test

Time  Mood  Reason  Category  Result(%)
0   888     2       1         2         20

In [60]:
loaded_model.predict(df_test)

array([2])